apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-deployment
  labels:
    app: Coursework
spec:
  selector:
    matchLabels:
      app: Coursework
  replicas: 2
  template:
    metadata:
      labels:
        app: Coursework
    spec:
      containers:
      - name: coursework
        image: localhost:32000/mycassandra:registry
        ports:
        - containerPort: 80